In [1]:
import numpy as np
import torch

In [2]:
data = [[0,1],[2,4]]
x_data = torch.tensor(data)

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8184, 0.7597, 0.7068],
        [0.6665, 0.0348, 0.3599]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
tensor = torch.rand(3,4)

print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.6704, 0.0413, 0.4620, 0.6017],
        [0.1497, 0.7914, 0.5928, 0.5635],
        [0.6858, 0.7322, 0.4303, 0.9663]])
torch.Size([3, 4])
torch.float32
cpu


In [25]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [26]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [27]:
print(tensor.mul(tensor))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [30]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [31]:
t = torch.ones(5)
n = t.numpy()
print(n)

[1. 1. 1. 1. 1.]


In [32]:
t.add_(1)
print(t,n)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [35]:
ST1 = np.array([[17.0 ,12 ,13 ,15 ,15 ,20 ,20],[ 10 ,12 ,14 ,15 ,20 ,15 ,20]]) # classe 1 
ST2 = np.array([4, 7.5, 10 ,11, 5 ,5 ,6, 8, 5, 0, 5, 0, 10, 6]).reshape(2,7) # classe 2

Xstudents = np.concatenate((ST1,ST2),axis=1)

Ystudents = np.ones(14)
Ystudents[7:] = 0

X = torch.FloatTensor(Xstudents.T)
Y = torch.FloatTensor(Ystudents)
 
print("Dimension de Y",Y.shape) ## 14
 
print("Dimension de X", X.shape) ## 14,2

Dimension de Y torch.Size([14])
Dimension de X torch.Size([14, 2])
